# Generated by Django 3.0.6 on 2021-03-29 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0004_auto_20210329_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regdriver',
            name='imgg',
        ),
    ]
