# Generated by Django 3.0.6 on 2021-03-29 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0005_remove_regdriver_imgg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='regdriver',
            old_name='model',
            new_name='car_model',
        ),
    ]
