# Generated by Django 3.0.6 on 2021-03-29 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0006_auto_20210330_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='regdriver',
            name='license',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
