# Generated by Django 3.0.6 on 2021-03-29 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0007_regdriver_license'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regdriver',
            name='license',
            field=models.FileField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
