# Generated by Django 3.0.6 on 2021-03-29 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0008_auto_20210330_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regdriver',
            name='license',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
