# Generated by Django 3.0.6 on 2021-03-30 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0009_auto_20210330_0239'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Regdriver',
        ),
    ]
