# Generated by Django 3.0.6 on 2021-04-10 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0011_coffee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='coffee',
        ),
        migrations.AlterField(
            model_name='driver',
            name='avatar',
            field=models.ImageField(default='avatar.png', upload_to='pics/'),
        ),
    ]
