# Generated by Django 3.0.6 on 2021-05-25 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0013_coffee'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedbackmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clean_car', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=8)),
                ('condition_of_seats', models.CharField(choices=[('very good', 'very good'), ('good', 'good'), ('fair', 'fair'), ('poor', 'poor'), ('very poor', 'very poor')], max_length=10)),
                ('Behaviour_of_Driver', models.CharField(choices=[('very good', 'very good'), ('good', 'good'), ('fair', 'fair'), ('poor', 'poor'), ('very poor', 'very poor')], max_length=10)),
                ('Driving_Skills', models.CharField(choices=[('very good', 'very good'), ('good', 'good'), ('fair', 'fair'), ('poor', 'poor'), ('very poor', 'very poor')], max_length=10)),
                ('Level_of_comfort', models.CharField(choices=[('very good', 'very good'), ('good', 'good'), ('fair', 'fair'), ('poor', 'poor'), ('very poor', 'very poor')], max_length=10)),
                ('recommend', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=8)),
            ],
        ),
    ]
