# Generated by Django 3.0.6 on 2021-03-30 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Regdriver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('email', models.EmailField(max_length=200, null=True)),
                ('contact', models.CharField(max_length=10, null=True)),
                ('car_model', models.CharField(max_length=20, null=True)),
                ('capacity', models.CharField(max_length=20, null=True)),
                ('license', models.ImageField(blank=True, null=True, upload_to='avatars/')),
            ],
        ),
    ]
