# Generated by Django 3.0.6 on 2021-03-30 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regdriver',
            name='license',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
