# Generated by Django 3.0.6 on 2021-03-30 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver2', '0002_auto_20210330_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='regdriver',
            name='password1',
            field=models.CharField(default='Shu', max_length=100),
        ),
        migrations.AddField(
            model_name='regdriver',
            name='password2',
            field=models.CharField(default='Shu', max_length=100),
        ),
    ]
