# Generated by Django 3.0.6 on 2021-03-30 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver2', '0004_auto_20210330_2112'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Regdriver',
        ),
    ]
