# Generated by Django 3.0.6 on 2021-04-01 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('driver2', '0005_delete_regdriver'),
    ]

    operations = [
        migrations.CreateModel(
            name='carformmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_location', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('type', models.CharField(choices=[('AC', 'Ac'), ('NonAC', 'NonAC')], max_length=8)),
                ('capacity', models.IntegerField(null=True)),
            ],
        ),
    ]
