# Generated by Django 3.0.6 on 2021-04-03 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver2', '0010_auto_20210403_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bikeformmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_location', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('start_time', models.CharField(max_length=255, null=True)),
                ('journey_time', models.CharField(max_length=255, null=True)),
                ('fare', models.IntegerField(null=True)),
                ('date', models.CharField(max_length=255, null=True)),
                ('capacity', models.IntegerField(default='1', editable=False, max_length=1)),
            ],
        ),
    ]
