# Generated by Django 3.0.6 on 2021-04-03 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('driver2', '0011_bikeformmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='carformmodel',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bikeformmodel',
            name='capacity',
            field=models.IntegerField(default='1', editable=False),
        ),
    ]
