# Generated by Django 3.0.6 on 2021-04-03 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver2', '0012_auto_20210403_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikeformmodel',
            name='license',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
