# Generated by Django 3.0.6 on 2021-04-04 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver2', '0015_bikeformmodel_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bikeformmodel',
            old_name='user',
            new_name='username',
        ),
    ]
