# Generated by Django 3.0.6 on 2021-04-04 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver2', '0016_auto_20210404_1145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bikeformmodel',
            old_name='username',
            new_name='user',
        ),
    ]
