# Generated by Django 3.0.6 on 2021-04-05 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver2', '0018_remove_carformmodel_license'),
    ]

    operations = [
        migrations.AddField(
            model_name='carformmodel',
            name='license',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
