# Generated by Django 3.0.6 on 2021-04-27 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver2', '0020_auto_20210410_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carformmodel',
            name='date',
            field=models.DateField(),
        ),
    ]
