# Generated by Django 3.0.6 on 2021-04-27 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver2', '0021_auto_20210427_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carformmodel',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
