# Generated by Django 3.0.6 on 2021-04-27 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver2', '0022_auto_20210427_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikeformmodel',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
