# Generated by Django 3.0.6 on 2021-04-28 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('driver2', '0025_auto_20210427_2143'),
    ]

    operations = [
        migrations.CreateModel(
            name='TruckformModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_location', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('start_time', models.CharField(max_length=255, null=True)),
                ('date', models.DateField(null=True)),
                ('no_of_cartoon', models.IntegerField(null=True)),
                ('license', models.ImageField(blank=True, null=True, upload_to='')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
