# Generated by Django 3.0.6 on 2021-05-20 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver2', '0026_truckformmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikeformmodel',
            name='contact_Number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='carformmodel',
            name='contact_Number',
            field=models.IntegerField(null=True),
        ),
    ]
