# Generated by Django 3.0.6 on 2021-05-20 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver2', '0027_auto_20210520_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikeformmodel',
            name='veh_number',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='carformmodel',
            name='veh_number',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='bikeformmodel',
            name='contact_Number',
            field=models.IntegerField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='carformmodel',
            name='contact_Number',
            field=models.IntegerField(max_length=10, null=True),
        ),
    ]
