# Generated by Django 3.0.6 on 2021-05-20 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver2', '0028_auto_20210520_1143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bikeformmodel',
            old_name='veh_number',
            new_name='vehicle_Number',
        ),
        migrations.RenameField(
            model_name='carformmodel',
            old_name='veh_number',
            new_name='vehicle_Number',
        ),
    ]
