# Generated by Django 3.0.6 on 2021-05-20 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver2', '0029_auto_20210520_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carformmodel',
            name='start_time',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
