# Generated by Django 3.0.6 on 2021-05-23 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver2', '0030_auto_20210520_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='truckformmodel',
            name='contact_Number',
            field=models.IntegerField(max_length=10, null=True),
        ),
    ]
